// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TranTheTuan/go-shortener/internal/repository (interfaces: PlanRepository,SubscriptionRepository,UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/repository/mock_repositories.go -package=mocksrepository github.com/TranTheTuan/go-shortener/internal/repository PlanRepository,SubscriptionRepository,UserRepository
//

// Package mocksrepository is a generated GoMock package.
package mocksrepository

import (
	context "context"
	reflect "reflect"

	repository "github.com/TranTheTuan/go-shortener/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPlanRepository is a mock of PlanRepository interface.
type MockPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepositoryMockRecorder
	isgomock struct{}
}

// MockPlanRepositoryMockRecorder is the mock recorder for MockPlanRepository.
type MockPlanRepositoryMockRecorder struct {
	mock *MockPlanRepository
}

// NewMockPlanRepository creates a new mock instance.
func NewMockPlanRepository(ctrl *gomock.Controller) *MockPlanRepository {
	mock := &MockPlanRepository{ctrl: ctrl}
	mock.recorder = &MockPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepository) EXPECT() *MockPlanRepositoryMockRecorder {
	return m.recorder
}

// GetByCode mocks base method.
func (m *MockPlanRepository) GetByCode(ctx context.Context, code string) (*repository.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*repository.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockPlanRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockPlanRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockPlanRepository) GetByID(ctx context.Context, id int64) (*repository.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*repository.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlanRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlanRepository)(nil).GetByID), ctx, id)
}

// GetByPaddlePriceID mocks base method.
func (m *MockPlanRepository) GetByPaddlePriceID(ctx context.Context, priceID string) (*repository.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPaddlePriceID", ctx, priceID)
	ret0, _ := ret[0].(*repository.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPaddlePriceID indicates an expected call of GetByPaddlePriceID.
func (mr *MockPlanRepositoryMockRecorder) GetByPaddlePriceID(ctx, priceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPaddlePriceID", reflect.TypeOf((*MockPlanRepository)(nil).GetByPaddlePriceID), ctx, priceID)
}

// List mocks base method.
func (m *MockPlanRepository) List(ctx context.Context) ([]*repository.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*repository.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPlanRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPlanRepository)(nil).List), ctx)
}

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// ClearCanceledAt mocks base method.
func (m *MockSubscriptionRepository) ClearCanceledAt(ctx context.Context, paddleSubID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCanceledAt", ctx, paddleSubID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCanceledAt indicates an expected call of ClearCanceledAt.
func (mr *MockSubscriptionRepositoryMockRecorder) ClearCanceledAt(ctx, paddleSubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCanceledAt", reflect.TypeOf((*MockSubscriptionRepository)(nil).ClearCanceledAt), ctx, paddleSubID)
}

// Create mocks base method.
func (m *MockSubscriptionRepository) Create(ctx context.Context, sub *repository.Subscription) (*repository.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sub)
	ret0, _ := ret[0].(*repository.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionRepositoryMockRecorder) Create(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionRepository)(nil).Create), ctx, sub)
}

// GetActiveByUserID mocks base method.
func (m *MockSubscriptionRepository) GetActiveByUserID(ctx context.Context, userID int64) (*repository.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(*repository.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByUserID indicates an expected call of GetActiveByUserID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByUserID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetActiveByUserID), ctx, userID)
}

// GetByPaddleSubscriptionID mocks base method.
func (m *MockSubscriptionRepository) GetByPaddleSubscriptionID(ctx context.Context, paddleSubID string) (*repository.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPaddleSubscriptionID", ctx, paddleSubID)
	ret0, _ := ret[0].(*repository.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPaddleSubscriptionID indicates an expected call of GetByPaddleSubscriptionID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetByPaddleSubscriptionID(ctx, paddleSubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPaddleSubscriptionID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetByPaddleSubscriptionID), ctx, paddleSubID)
}

// GetByUserID mocks base method.
func (m *MockSubscriptionRepository) GetByUserID(ctx context.Context, userID int64) ([]*repository.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*repository.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetByUserID), ctx, userID)
}

// UpsertByPaddleID mocks base method.
func (m *MockSubscriptionRepository) UpsertByPaddleID(ctx context.Context, sub *repository.Subscription) (*repository.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertByPaddleID", ctx, sub)
	ret0, _ := ret[0].(*repository.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertByPaddleID indicates an expected call of UpsertByPaddleID.
func (mr *MockSubscriptionRepositoryMockRecorder) UpsertByPaddleID(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertByPaddleID", reflect.TypeOf((*MockSubscriptionRepository)(nil).UpsertByPaddleID), ctx, sub)
}

// UpsertByUserID mocks base method.
func (m *MockSubscriptionRepository) UpsertByUserID(ctx context.Context, sub *repository.Subscription) (*repository.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertByUserID", ctx, sub)
	ret0, _ := ret[0].(*repository.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertByUserID indicates an expected call of UpsertByUserID.
func (mr *MockSubscriptionRepositoryMockRecorder) UpsertByUserID(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertByUserID", reflect.TypeOf((*MockSubscriptionRepository)(nil).UpsertByUserID), ctx, sub)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *repository.User) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// CreateWithSubscription mocks base method.
func (m *MockUserRepository) CreateWithSubscription(ctx context.Context, user *repository.User, sub *repository.Subscription) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithSubscription", ctx, user, sub)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithSubscription indicates an expected call of CreateWithSubscription.
func (mr *MockUserRepositoryMockRecorder) CreateWithSubscription(ctx, user, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithSubscription", reflect.TypeOf((*MockUserRepository)(nil).CreateWithSubscription), ctx, user, sub)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id int64) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetByKeycloakSub mocks base method.
func (m *MockUserRepository) GetByKeycloakSub(ctx context.Context, sub string) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKeycloakSub", ctx, sub)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKeycloakSub indicates an expected call of GetByKeycloakSub.
func (mr *MockUserRepositoryMockRecorder) GetByKeycloakSub(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKeycloakSub", reflect.TypeOf((*MockUserRepository)(nil).GetByKeycloakSub), ctx, sub)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(ctx context.Context, username string) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), ctx, username)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context) ([]*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *repository.User) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}

// UpdatePaddleCustomerID mocks base method.
func (m *MockUserRepository) UpdatePaddleCustomerID(ctx context.Context, userID int64, customerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaddleCustomerID", ctx, userID, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaddleCustomerID indicates an expected call of UpdatePaddleCustomerID.
func (mr *MockUserRepositoryMockRecorder) UpdatePaddleCustomerID(ctx, userID, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaddleCustomerID", reflect.TypeOf((*MockUserRepository)(nil).UpdatePaddleCustomerID), ctx, userID, customerID)
}
