// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TranTheTuan/go-shortener/internal/service (interfaces: QuotaService)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/service/mock_quota_service.go -package=mocksservice github.com/TranTheTuan/go-shortener/internal/service QuotaService
//

// Package mocksservice is a generated GoMock package.
package mocksservice

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuotaService is a mock of QuotaService interface.
type MockQuotaService struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaServiceMockRecorder
	isgomock struct{}
}

// MockQuotaServiceMockRecorder is the mock recorder for MockQuotaService.
type MockQuotaServiceMockRecorder struct {
	mock *MockQuotaService
}

// NewMockQuotaService creates a new mock instance.
func NewMockQuotaService(ctrl *gomock.Controller) *MockQuotaService {
	mock := &MockQuotaService{ctrl: ctrl}
	mock.recorder = &MockQuotaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaService) EXPECT() *MockQuotaServiceMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockQuotaService) Allow(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockQuotaServiceMockRecorder) Allow(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockQuotaService)(nil).Allow), ctx, userID)
}

// Release mocks base method.
func (m *MockQuotaService) Release(ctx context.Context, userID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release", ctx, userID)
}

// Release indicates an expected call of Release.
func (mr *MockQuotaServiceMockRecorder) Release(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockQuotaService)(nil).Release), ctx, userID)
}

// Remaining mocks base method.
func (m *MockQuotaService) Remaining(ctx context.Context, userID int64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remaining", ctx, userID)
	ret0, _ := ret[0].(int)
	return ret0
}

// Remaining indicates an expected call of Remaining.
func (mr *MockQuotaServiceMockRecorder) Remaining(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remaining", reflect.TypeOf((*MockQuotaService)(nil).Remaining), ctx, userID)
}

// Reset mocks base method.
func (m *MockQuotaService) Reset(ctx context.Context, userID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset", ctx, userID)
}

// Reset indicates an expected call of Reset.
func (mr *MockQuotaServiceMockRecorder) Reset(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockQuotaService)(nil).Reset), ctx, userID)
}
